- name: Deploy docker-compose and configs
  template:
    src: docker-compose.yml
    dest:  "{{ base_dir }}/docker-compose.yml"
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_name }}"
    mode: '0644'

- name: Start docker stack
  shell: "docker compose -f {{ base_dir }}/docker-compose.yml up -d --remove-orphans"