---
- Infrastructure:
    - Pi-hole:
        icon: pi-hole.png
        href: "http://192.168.72.130:8053/admin"
        description: Local DNS
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: "http://192.168.72.130:81"
        description: Reverse Proxy