---
- Infrastructure:
    - Pi-hole:
        icon: pi-hole.png
        href: "http://dns.voxlab.lan/admin"
        description: Local DNS
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: "http://proxy.voxlab.lan"
        description: Reverse Proxy
    - Memos:
        icon: memos.png
        href: "http://memos.voxlab.lan"
        description: Personal notes
    - Portainer:
        icon: portainer.png
        href: "http://portainer.voxlab.lan"
        description: Docker management
    - Uptime Kyma:
        icon: uptime-kuma.png
        href: "http://status.voxlab.lan"
        description: Monitoring
    - Mealie:
        icon: mealie.png
        href: "http://mealie.voxlab.lan"
        description: Recipe planner