---
- Infrastructure:
    - Pi-hole:
        icon: pi-hole.png
        href: "http://dns.voxlab.lan/admin"
        description: Local DNS
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: "http://proxy.voxlab.lan"
        description: Reverse Proxy