---
- Infrastructure:
    - Pi-hole:
        icon: pi-hole.png
        href: "https://dns.voxlb.com/admin"
        description: Local DNS
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: "https://proxy.voxlb.com"
        description: Reverse Proxy
    - Memos:
        icon: memos.png
        href: "https://memos.voxlb.com"
        description: Personal notes
    - Portainer:
        icon: portainer.png
        href: "https://portainer.voxlb.com"
        description: Docker management
    - Uptime Kyma:
        icon: uptime-kuma.png
        href: "https://status.voxlb.com"
        description: Monitoring
    - Mealie:
        icon: mealie.png
        href: "https://mealie.voxlb.com"
        description: Recipe planner