---
title: VoxLab Dashboard

base: http://dashboard.voxlab.lan

hideHost: true
allowIframe: true
disableHostname: false

layout:
    Infrastructure:
        style: row
        columns: 3

connectivityTest: true