---
title: VoxLab Dashboard

base: https://dashboard.voxlb.com

proxied: true
hideHost: true
allowIframe: true
disableHostname: false

background: /images/background.jpg

cardBlur: sm
theme: dark

layout:
    Infrastructure:
        style: row
        columns: 3

connectivityTest: true