---
title: VoxLab Dashboard

base: http://dashboard.voxlab.lan

hideHost: true
allowIframe: true
disableHostname: false

background: /images/background.jpg

cardBlur: sm
theme: dark

layout:
    Infrastructure:
        style: row
        columns: 3

connectivityTest: true